### PR TITLE
[CI skip] Add jimbudarz to maintainers

### PR DESCRIPTION
**Pull request by jimbudarz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@halldc any comments?

**Comment by jimbudarz** [comment]
@davidchall I think @halldc is your alter ego!
Do you want to switch the maintainer user of this feedstock to your other identity?

**Comment by jimbudarz** [comment]
@beckermr, how long should we give him?

**Comment by beckermr** [comment]
Oh sorry I forgot about this one. Thank you for the reminder. Let's merge.

**Pull request merged**
